export * from './home/home.component';
export * from './page-not-found/page-not-found.component';
export * from './result-page/result-page.component';
export * from './how-it-works/how-it-works.component';
export * from './how-to-do/how-to-do.component';
export * from './boards-list/boards-list.component';
export * from './board-results/board-results.component';
export * from './latest-results/latest-results.component';
export * from './slider/slider.component';
